version: "3.9"

services:
  api:
    build: .
    container_name: balligh_api
    restart: always

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: "postgresql://baligh_user:wWXv80X2lG2ZGMnvkK8LF25wfVr0SwJh@dpg-d8p51677f7vs73cjvv50-a.oregon-postgres.render.com:5432/baligh_db_ange?sslmode=require"
      SECRET_KEY: "supersecret"
      UPLOAD_DIR: "uploads"

    volumes:
      - .:/app
      - uploads_data:/app/uploads

    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  uploads_data: